repos:
  - repo: https://github.com/semgrep/pre-commit
    rev: 'v1.142.0'
    hooks:
      - id: semgrep
        entry: semgrep
        args: ['--config', 'auto', '--error', '--skip-unknown-extensions']
